services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=apigateway,lambda,dynamodb,sqs,s3,sns
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./lambda_criar_pedido:/etc/localstack/init/lambda_criar_pedido
      - ./lambda_processar_pedido:/etc/localstack/init/lambda_processar_pedido
      - .:/app 

  setup-resources:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - ENDPOINT_URL=http://localstack:4566
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: >
      /bin/sh -c "
        yum install -y zip && 
        echo 'Aguardando LocalStack...' && 
        sleep 10 && 
        chmod +x setup.sh && 
        ./setup.sh
      "

  app-cliente:
    # ATUALIZADO: De python:3.9-slim para python:3.11-slim
    image: python:3.11-slim
    depends_on:
      - localstack
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    command: >
      bash -c "pip install requests boto3 && tail -f /dev/null"